/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package msys.client;

import javafx.application.Application;
import javafx.stage.Stage;
import msys.client.communication.Client;
import msys.client.stages.Login;
import msys.client.stages.Project;
import org.apache.commons.configuration2.PropertiesConfiguration;
import org.apache.commons.configuration2.builder.fluent.Configurations;
import org.apache.commons.configuration2.ex.ConfigurationException;

public class App extends Application {
    private Client client = new Client();
    private Login login_stage= new Login();
    private Project project_stage;
    public static PropertiesConfiguration config = new PropertiesConfiguration();

    public void start(Stage stage) {
        Configurations configurations = new Configurations();
        try {
            var file = getClass().getResource("/config.properties").toExternalForm();
            System.out.println(file);
            config = configurations.properties(file);
        } catch (ConfigurationException e) {
            e.printStackTrace();
        }
        project_stage = new Project();
        //It will show the output
        project_stage.show();
        //It will show the output until stage object closed
        // login_stage.showAndWait();//TODO implement later
    }

    public static void main(String[] args) {
        launch(args);
    }
}
